"""
metrics.py

Evaluation Metrics for Comparing Generative Models
===================================================

This module provides evaluation metrics for both point cloud and image
data generated by flow matching models.

Point Data Metrics
------------------
- Wasserstein-2 distance (exact via POT, or sliced approximation)
- Maximum Mean Discrepancy (MMD)
- Multi-scale MMD (more robust)
- Coverage and density (k-NN based)

Image Data Metrics
------------------
- Sliced Wasserstein Distance (SWD)
- Per-channel SWD for RGB images
- Basic image statistics

Usage
-----
>>> from ads_cft.metrics import compute_metrics
>>> metrics = compute_metrics(real_samples, generated_samples, is_image=False)
>>> print(f"Wasserstein-2: {metrics['wasserstein_2d']:.4f}")
>>> print(f"MMD: {metrics['mmd_rbf']:.4f}")
"""

from __future__ import annotations

from typing import Dict, Optional, Tuple

import numpy as np
import torch

# Optional scipy import for advanced metrics
try:
    from scipy import linalg
    from scipy.spatial import cKDTree
    from scipy.stats import gaussian_kde

    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False
    cKDTree = None
    gaussian_kde = None

# Optional POT import for Wasserstein-2
try:
    import ot
    POT_AVAILABLE = True
except ImportError:
    POT_AVAILABLE = False
    ot = None

# Optional sklearn import for PCA (used in NLL computation)
try:
    from sklearn.decomposition import PCA
    SKLEARN_AVAILABLE = True
except ImportError:
    PCA = None
    SKLEARN_AVAILABLE = False

# Optional torchvision import for FID computation
try:
    import torchvision.models as tv_models
    import torchvision.transforms as tv_transforms
    TORCHVISION_AVAILABLE = True
except ImportError:
    tv_models = None
    tv_transforms = None
    TORCHVISION_AVAILABLE = False

Tensor = torch.Tensor


# =============================================================================
# Point Cloud Metrics
# =============================================================================


def wasserstein_1d_w2(x: np.ndarray, y: np.ndarray) -> float:
    """
    Compute 1D Wasserstein-2 distance.

    For 1D distributions, W2 = sqrt(mean((sort(x) - sort(y))^2)).
    This is the closed-form solution for 1D optimal transport with L2 cost.

    Args:
        x: First set of samples (N,)
        y: Second set of samples (M,)

    Returns:
        1D Wasserstein-2 distance
    """
    x = np.sort(x.flatten())
    y = np.sort(y.flatten())
    
    # Handle different sample sizes by interpolation
    n, m = len(x), len(y)
    if n != m:
        # Interpolate to same size
        size = min(n, m)
        x_idx = np.linspace(0, n - 1, size).astype(int)
        y_idx = np.linspace(0, m - 1, size).astype(int)
        x = x[x_idx]
        y = y[y_idx]
    
    return np.sqrt(np.mean((x - y) ** 2))


def sliced_wasserstein_2d(real: np.ndarray, gen: np.ndarray, n_projections: int = 100) -> float:
    """
    Sliced Wasserstein-2 distance for 2D point clouds.

    Projects onto random 1D directions and computes average 1D W2.
    This is a fast approximation to the true 2D Wasserstein-2 distance.

    Args:
        real: (N, 2) real samples
        gen: (M, 2) generated samples
        n_projections: Number of random projections

    Returns:
        Sliced W2 distance
    """
    # Random projection directions
    theta = np.linspace(0, np.pi, n_projections, endpoint=False)
    directions = np.stack([np.cos(theta), np.sin(theta)], axis=1)  # (n_proj, 2)

    # Project and compute 1D W2
    distances = []
    for d in directions:
        proj_real = real @ d  # (N,)
        proj_gen = gen @ d  # (M,)
        distances.append(wasserstein_1d_w2(proj_real, proj_gen))

    return np.mean(distances)


def wasserstein_2d_exact(real: np.ndarray, gen: np.ndarray) -> float:
    """
    Exact Wasserstein-2 distance using POT (Python Optimal Transport).

    Computes the true optimal transport distance with squared Euclidean cost.
    This is slower than sliced W2 but exact.

    Args:
        real: (N, D) real samples
        gen: (M, D) generated samples

    Returns:
        Exact W2 distance, or -1 if POT unavailable
    """
    if not POT_AVAILABLE:
        return -1.0
    
    n, m = len(real), len(gen)
    
    # Uniform weights
    a = np.ones(n) / n
    b = np.ones(m) / m
    
    # Cost matrix (squared Euclidean distances)
    M = ot.dist(real, gen, metric='sqeuclidean')
    
    # Compute W2^2 using EMD
    w2_squared = ot.emd2(a, b, M)
    
    return np.sqrt(w2_squared)


def wasserstein_2d(real: np.ndarray, gen: np.ndarray) -> float:
    """
    Compute 2D Wasserstein-2 distance.

    Uses exact W2 if POT is available and sample size is reasonable,
    otherwise falls back to sliced W2.

    Args:
        real: (N, 2) real samples
        gen: (M, 2) generated samples

    Returns:
        W2 distance
    """
    n, m = len(real), len(gen)
    
    # Use exact W2 if POT is available (up to 15k samples)
    if POT_AVAILABLE and n <= 15000 and m <= 15000:
        return wasserstein_2d_exact(real, gen)
    else:
        return sliced_wasserstein_2d(real, gen)


def compute_mmd(
    x: Tensor,
    y: Tensor,
    kernel: str = "rbf",
    sigma: Optional[float] = None,
) -> float:
    """
    Maximum Mean Discrepancy between two distributions.

    MMD is a kernel-based distance metric that measures the difference
    between two probability distributions in a reproducing kernel
    Hilbert space (RKHS).

    Args:
        x: (N, D) samples from distribution P
        y: (M, D) samples from distribution Q
        kernel: Kernel type ('rbf' or 'linear')
        sigma: RBF kernel bandwidth (if None, uses median heuristic)

    Returns:
        MMD estimate (non-negative)

    Example
    -------
    >>> x = torch.randn(1000, 2)  # samples from P
    >>> y = torch.randn(1000, 2) + 0.5  # samples from Q (shifted)
    >>> mmd = compute_mmd(x, y)
    """
    x = x.float()
    y = y.float()

    # Median heuristic for bandwidth if not specified
    if sigma is None and kernel == "rbf":
        with torch.no_grad():
            dists = torch.cdist(x, y, p=2)
            sigma = float(dists.median())
            if sigma < 1e-6:
                sigma = 1.0

    def rbf_kernel(a: Tensor, b: Tensor, sigma: float) -> Tensor:
        dist_sq = torch.cdist(a, b, p=2) ** 2
        return torch.exp(-dist_sq / (2 * sigma ** 2))

    if kernel == "rbf":
        k_xx = rbf_kernel(x, x, sigma)
        k_yy = rbf_kernel(y, y, sigma)
        k_xy = rbf_kernel(x, y, sigma)
    else:  # linear kernel
        k_xx = x @ x.T
        k_yy = y @ y.T
        k_xy = x @ y.T

    n, m = x.shape[0], y.shape[0]

    # Unbiased estimate of MMD²
    mmd = (k_xx.sum() - k_xx.trace()) / (n * (n - 1))
    mmd += (k_yy.sum() - k_yy.trace()) / (m * (m - 1))
    mmd -= 2 * k_xy.mean()

    # MMD² can be slightly negative due to finite sample bias; clamp to 0
    return float(max(0.0, mmd))


def compute_mmd_multiscale(x: Tensor, y: Tensor) -> float:
    """
    Multi-scale MMD using multiple RBF bandwidths.

    More robust than single-bandwidth MMD as it captures
    both fine and coarse distribution differences.

    Uses bandwidths at [0.1, 0.5, 1.0, 2.0, 10.0] × median distance.

    Args:
        x: (N, D) samples from P
        y: (M, D) samples from Q

    Returns:
        Multi-scale MMD estimate (non-negative)

    Example
    -------
    >>> mmd = compute_mmd_multiscale(real_samples, gen_samples)
    """
    x = x.float()
    y = y.float()

    # Compute median distance for scale reference
    with torch.no_grad():
        dists = torch.cdist(x, y, p=2)
        median_dist = float(dists.median())
        if median_dist < 1e-6:
            median_dist = 1.0

    # Multiple bandwidths around the median
    sigmas = [median_dist * scale for scale in [0.1, 0.5, 1.0, 2.0, 10.0]]

    mmd_total = 0.0
    for sigma in sigmas:
        mmd_total += compute_mmd(x, y, kernel="rbf", sigma=sigma)

    return mmd_total / len(sigmas)


def compute_coverage_density(
    real: Tensor,
    gen: Tensor,
    k: int = 5,
) -> Tuple[float, float]:
    """
    Coverage and Density metrics using k-NN.

    Coverage: fraction of real samples with a generated neighbor within threshold
    Density: average number of generated samples near each real sample

    The threshold is computed as the median k-NN distance in the real data.

    Args:
        real: (N, D) real samples
        gen: (M, D) generated samples
        k: Number of nearest neighbors

    Returns:
        Tuple of (coverage, density), or (-1, -1) if scipy unavailable

    Example
    -------
    >>> coverage, density = compute_coverage_density(real, gen, k=5)
    >>> print(f"Coverage: {coverage:.2%}, Density: {density:.4f}")
    """
    if not SCIPY_AVAILABLE:
        return -1.0, -1.0

    real_np = real.cpu().numpy()
    gen_np = gen.cpu().numpy()

    # Build KD-trees
    real_tree = cKDTree(real_np)
    gen_tree = cKDTree(gen_np)

    # Compute threshold as median k-NN distance in real data
    real_dists, _ = real_tree.query(real_np, k=k + 1)  # +1 because self is included
    threshold = np.median(real_dists[:, -1])

    # Coverage: fraction of real samples with a generated neighbor within threshold
    real_to_gen_dists, _ = gen_tree.query(real_np, k=1)
    coverage = (real_to_gen_dists < threshold).mean()

    # Density: avg generated samples within threshold of real
    real_to_gen_counts = gen_tree.query_ball_point(real_np, threshold)
    density = np.mean([len(c) for c in real_to_gen_counts]) / len(gen_np)

    return float(coverage), float(density)


def compute_point_metrics(
    real: Tensor,
    gen: Tensor,
    compute_expensive: bool = True,
    checkerboard_config: Optional[Dict] = None,
) -> Dict[str, float]:
    """
    Compute all point cloud metrics.

    Args:
        real: (N, D) real samples
        gen: (M, D) generated samples
        compute_expensive: If True, compute coverage/density (slower)
        checkerboard_config: If provided, compute checkerboard metrics.
            Should contain keys: domain, cell_size, parity, lam, mu

    Returns:
        Dictionary of metrics including:
        - real_mean_x, real_mean_y: Mean of real samples
        - gen_mean_x, gen_mean_y: Mean of generated samples
        - real_std, gen_std: Standard deviation
        - wasserstein_2d: Sliced 2D Wasserstein distance
        - wasserstein_x, wasserstein_y: Per-dimension Wasserstein-2
        - mmd_rbf: RBF kernel MMD
        - mmd_multiscale: Multi-scale MMD
        - coverage, density: k-NN based metrics (if compute_expensive)
        - BV, JS_cell, WED, WED_norm, CQS: Checkerboard metrics (if checkerboard_config)

    Example
    -------
    >>> metrics = compute_point_metrics(real_samples, gen_samples)
    >>> print(f"W2: {metrics['wasserstein_2d']:.4f}, MMD: {metrics['mmd_rbf']:.4f}")
    
    >>> # With checkerboard metrics
    >>> cb_config = {"domain": (-4, 4, -4, 4), "cell_size": 1.0, "parity": 0}
    >>> metrics = compute_point_metrics(real, gen, checkerboard_config=cb_config)
    >>> print(f"CQS: {metrics['CQS']:.4f}")
    """
    real_np = real.cpu().numpy()
    gen_np = gen.cpu().numpy()

    metrics: Dict[str, float] = {}

    # Basic statistics
    metrics["real_mean_x"] = float(real_np[:, 0].mean())
    metrics["real_mean_y"] = (
        float(real_np[:, 1].mean()) if real_np.shape[1] > 1 else 0.0
    )
    metrics["gen_mean_x"] = float(gen_np[:, 0].mean())
    metrics["gen_mean_y"] = float(gen_np[:, 1].mean()) if gen_np.shape[1] > 1 else 0.0

    metrics["real_std"] = float(real_np.std())
    metrics["gen_std"] = float(gen_np.std())

    # Wasserstein distance
    if real_np.shape[1] == 2:
        # Always compute sliced W2 (fast approximation)
        metrics["swd_2d"] = sliced_wasserstein_2d(real_np, gen_np)
        # Compute exact W2 if POT available
        if POT_AVAILABLE:
            metrics["wasserstein_2d"] = wasserstein_2d_exact(real_np, gen_np)
        else:
            metrics["wasserstein_2d"] = metrics["swd_2d"]  # fallback to SWD
    metrics["wasserstein_x"] = wasserstein_1d_w2(real_np[:, 0], gen_np[:, 0])
    if real_np.shape[1] > 1:
        metrics["wasserstein_y"] = wasserstein_1d_w2(real_np[:, 1], gen_np[:, 1])

    # MMD with median heuristic for bandwidth
    metrics["mmd_rbf"] = compute_mmd(real, gen, kernel="rbf")

    # Multi-scale MMD (more robust)
    metrics["mmd_multiscale"] = compute_mmd_multiscale(real, gen)

    # Coverage and density (can be slow for large datasets)
    if compute_expensive and len(real) > 10 and len(gen) > 10:
        try:
            coverage, density = compute_coverage_density(real, gen)
            metrics["coverage"] = coverage
            metrics["density"] = density
        except Exception:
            metrics["coverage"] = -1.0
            metrics["density"] = -1.0
    
    # Checkerboard-specific metrics
    if checkerboard_config is not None:
        try:
            cb_metrics = compute_checkerboard_metrics(
                X_real=real_np,
                X_gen=gen_np,
                domain=checkerboard_config.get("domain", (-4.0, 4.0, -4.0, 4.0)),
                cell_size=checkerboard_config.get("cell_size", 1.0),
                parity=checkerboard_config.get("parity", 0),
                alpha=checkerboard_config.get("alpha", 1e-6),
                min_points_cell=checkerboard_config.get("min_points_cell", 5),
                max_points_cell=checkerboard_config.get("max_points_cell", None),
                lam=checkerboard_config.get("lam", 1.0),
                mu=checkerboard_config.get("mu", 1.0),
            )
            metrics.update(cb_metrics)
        except Exception as e:
            print(f"[WARNING] Checkerboard metrics computation failed: {e}")

    return metrics


# =============================================================================
# Checkerboard Quality Metrics (BV, JS, WED, CQS)
# =============================================================================


def checkerboard_valid_mask(Nx: int, Ny: int, parity: int = 0) -> np.ndarray:
    """
    Create a boolean mask for valid checkerboard cells.
    
    Args:
        Nx: Number of cells in x direction
        Ny: Number of cells in y direction
        parity: 0 or 1, determines which tiles are valid
        
    Returns:
        (Nx, Ny) boolean array where True indicates a valid cell
    """
    ii = np.arange(Nx)[:, None]
    jj = np.arange(Ny)[None, :]
    return ((ii + jj) % 2) == parity


def points_to_cells(
    X: np.ndarray,
    xmin: float,
    ymin: float,
    cell_size: float,
    Nx: int,
    Ny: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Map points to cell indices and determine in-domain status.
    
    Args:
        X: (N, 2) array of points
        xmin: Minimum x coordinate of domain
        ymin: Minimum y coordinate of domain
        cell_size: Size of each cell
        Nx: Number of cells in x direction
        Ny: Number of cells in y direction
        
    Returns:
        i: (N,) cell x-indices (clamped to valid range)
        j: (N,) cell y-indices (clamped to valid range)
        in_domain: (N,) boolean mask for points within the domain
    """
    x, y = X[:, 0], X[:, 1]
    
    # Check if points are within domain bounds
    xmax = xmin + Nx * cell_size
    ymax = ymin + Ny * cell_size
    in_domain = (x >= xmin) & (x < xmax) & (y >= ymin) & (y < ymax)
    
    # Compute cell indices
    i = np.floor((x - xmin) / cell_size).astype(int)
    j = np.floor((y - ymin) / cell_size).astype(int)
    
    # Clamp indices for safe indexing (out-of-domain handled by in_domain mask)
    i = np.clip(i, 0, Nx - 1)
    j = np.clip(j, 0, Ny - 1)
    
    return i, j, in_domain


def js_divergence(p: np.ndarray, q: np.ndarray, eps: float = 1e-12) -> float:
    """
    Compute Jensen-Shannon divergence between two probability distributions.
    
    JS(p, q) = 0.5 * KL(p || m) + 0.5 * KL(q || m), where m = 0.5 * (p + q)
    
    Args:
        p: First probability distribution (must sum to 1)
        q: Second probability distribution (must sum to 1)
        eps: Small constant for numerical stability
        
    Returns:
        JS divergence (in [0, log(2)] for natural log)
    """
    # Ensure non-negative and normalized
    p = np.clip(p, eps, 1.0)
    q = np.clip(q, eps, 1.0)
    p = p / p.sum()
    q = q / q.sum()
    
    m = 0.5 * (p + q)
    
    # KL divergences
    kl_pm = np.sum(p * (np.log(p) - np.log(m)))
    kl_qm = np.sum(q * (np.log(q) - np.log(m)))
    
    return 0.5 * (kl_pm + kl_qm)


def energy_distance_unbiased(X: np.ndarray, Y: np.ndarray) -> float:
    """
    Compute unbiased estimator of energy distance between two point sets.
    
    ED²(P, Q) = 2*E||X - Y|| - E||X - X'|| - E||Y - Y'||
    
    Uses unbiased U-statistic estimator (excludes diagonal terms).
    
    Args:
        X: (n, 2) samples from distribution P
        Y: (m, 2) samples from distribution Q
        
    Returns:
        Energy distance (ED, not squared), or NaN if insufficient points
    """
    n, m = len(X), len(Y)
    
    if n < 2 or m < 2:
        return np.nan
    
    # Pairwise distances
    d_xy = np.linalg.norm(X[:, None, :] - Y[None, :, :], axis=-1)  # (n, m)
    d_xx = np.linalg.norm(X[:, None, :] - X[None, :, :], axis=-1)  # (n, n)
    d_yy = np.linalg.norm(Y[:, None, :] - Y[None, :, :], axis=-1)  # (m, m)
    
    term_xy = 2.0 * d_xy.mean()
    
    # Unbiased within-distribution terms (exclude diagonal)
    term_xx = (d_xx.sum() - np.trace(d_xx)) / (n * (n - 1))
    term_yy = (d_yy.sum() - np.trace(d_yy)) / (m * (m - 1))
    
    ed2 = term_xy - term_xx - term_yy
    ed2 = max(ed2, 0.0)  # Numerical safety
    
    return np.sqrt(ed2)


def compute_checkerboard_metrics(
    X_real: np.ndarray,
    X_gen: np.ndarray,
    domain: Tuple[float, float, float, float] = (-4.0, 4.0, -4.0, 4.0),
    cell_size: float = 1.0,
    parity: int = 0,
    alpha: float = 1e-6,
    min_points_cell: int = 5,
    max_points_cell: Optional[int] = None,
    lam: float = 1.0,
    mu: float = 1.0,
) -> Dict[str, float]:
    """
    Compute checkerboard-specific quality metrics.
    
    Computes four metrics:
    1. BV (Boundary Violation): Fraction of generated points outside valid cells
    2. JS_cell: Jensen-Shannon divergence of cell occupancy distributions
    3. WED (Within-cell Energy Distance): Weighted average ED inside cells
    4. CQS (Checkerboard Quality Score): Composite metric = JS + λ*BV + μ*WED_norm
    
    Args:
        X_real: (N, 2) real samples
        X_gen: (M, 2) generated samples
        domain: (xmin, xmax, ymin, ymax) bounding box
        cell_size: Size of each checkerboard cell
        parity: 0 or 1, determines which tiles are valid
        alpha: Dirichlet smoothing for histogram (prevents log(0))
        min_points_cell: Minimum real points in cell to compute ED
        max_points_cell: Optional cap on points per cell for speed
        lam: Weight for BV in CQS
        mu: Weight for WED_norm in CQS
        
    Returns:
        Dictionary containing:
        - BV: Boundary violation rate [0, 1]
        - JS_cell: Cell occupancy JS divergence [0, log(2)]
        - WED: Weighted within-cell energy distance
        - WED_norm: WED normalized by cell_size
        - CQS: Composite quality score (lower is better)
        - Nx, Ny: Number of cells in each direction
        - num_valid_cells: Number of valid checkerboard cells
        - real_valid_frac: Fraction of real points in valid cells
        - gen_valid_frac: Fraction of generated points in valid cells
    """
    xmin, xmax, ymin, ymax = domain
    Nx = int(np.floor((xmax - xmin) / cell_size))
    Ny = int(np.floor((ymax - ymin) / cell_size))
    
    # Create valid cell mask
    valid = checkerboard_valid_mask(Nx, Ny, parity=parity)
    
    # Map points to cells
    ir, jr, inr = points_to_cells(X_real, xmin, ymin, cell_size, Nx, Ny)
    ig, jg, ing = points_to_cells(X_gen, xmin, ymin, cell_size, Nx, Ny)
    
    # Validity of each point (in-domain AND in valid cell)
    real_valid = inr & valid[ir, jr]
    gen_valid = ing & valid[ig, jg]
    
    # =========================================================================
    # 1) Boundary Violation (BV)
    # =========================================================================
    BV = 1.0 - gen_valid.mean()
    
    # =========================================================================
    # 2) Cell Occupancy JS Divergence
    # =========================================================================
    # Build list of valid cell indices
    valid_cells = np.argwhere(valid)  # (V, 2) with [i, j]
    V = len(valid_cells)
    
    # Map (i, j) -> linear valid-cell id
    id_map = -np.ones((Nx, Ny), dtype=int)
    id_map[valid] = np.arange(V)
    
    # Get valid-cell IDs for valid points
    rid = id_map[ir[real_valid], jr[real_valid]]
    gid = id_map[ig[gen_valid], jg[gen_valid]]
    
    # Count points per valid cell with Dirichlet smoothing
    pr_counts = np.bincount(rid, minlength=V).astype(float) + alpha
    pg_counts = np.bincount(gid, minlength=V).astype(float) + alpha
    
    # Normalize to probability distributions
    pr = pr_counts / pr_counts.sum()
    pg = pg_counts / pg_counts.sum()
    
    JS_cell = js_divergence(pr, pg)
    
    # =========================================================================
    # 3) Within-cell Energy Distance (weighted by real occupancy)
    # =========================================================================
    # Collect indices per valid cell
    real_by_cell = [[] for _ in range(V)]
    gen_by_cell = [[] for _ in range(V)]
    
    real_idx = np.where(real_valid)[0]
    gen_idx = np.where(gen_valid)[0]
    
    for idx in real_idx:
        cid = id_map[ir[idx], jr[idx]]
        real_by_cell[cid].append(idx)
    
    for idx in gen_idx:
        cid = id_map[ig[idx], jg[idx]]
        gen_by_cell[cid].append(idx)
    
    ed_list = []
    w_list = []
    
    for c in range(V):
        r_idx = real_by_cell[c]
        g_idx = gen_by_cell[c]
        
        # Skip cells with too few real points
        if len(r_idx) < min_points_cell:
            continue
        
        # Skip cells with too few generated points (let JS capture this)
        if len(g_idx) < 2:
            continue
        
        Xc = X_real[np.array(r_idx)]
        Yc = X_gen[np.array(g_idx)]
        
        # Optional cap on points per cell for speed
        if max_points_cell is not None:
            if len(Xc) > max_points_cell:
                idx_sample = np.random.choice(len(Xc), max_points_cell, replace=False)
                Xc = Xc[idx_sample]
            if len(Yc) > max_points_cell:
                idx_sample = np.random.choice(len(Yc), max_points_cell, replace=False)
                Yc = Yc[idx_sample]
        
        ed = energy_distance_unbiased(Xc, Yc)
        
        if np.isnan(ed):
            continue
        
        # Weight by real cell probability
        w = pr[c]
        ed_list.append(ed)
        w_list.append(w)
    
    if len(ed_list) == 0:
        WED = np.nan
        WED_norm = np.nan
    else:
        w = np.array(w_list)
        w = w / w.sum()  # Re-normalize weights
        WED = float(np.sum(w * np.array(ed_list)))
        WED_norm = WED / cell_size  # Dimensionless
    
    # =========================================================================
    # 4) Composite Checkerboard Quality Score (CQS)
    # =========================================================================
    CQS = JS_cell + lam * BV + (mu * WED_norm if not np.isnan(WED_norm) else 0.0)
    
    return {
        "BV": float(BV),
        "JS_cell": float(JS_cell),
        "WED": float(WED) if not np.isnan(WED) else None,
        "WED_norm": float(WED_norm) if not np.isnan(WED_norm) else None,
        "CQS": float(CQS),
        "Nx": Nx,
        "Ny": Ny,
        "num_valid_cells": V,
        "real_valid_frac": float(real_valid.mean()),
        "gen_valid_frac": float(gen_valid.mean()),
    }


def compute_checkerboard_metrics_torch(
    real: Tensor,
    gen: Tensor,
    domain: Tuple[float, float, float, float] = (-4.0, 4.0, -4.0, 4.0),
    cell_size: float = 1.0,
    parity: int = 0,
    alpha: float = 1e-6,
    min_points_cell: int = 5,
    max_points_cell: Optional[int] = None,
    lam: float = 1.0,
    mu: float = 1.0,
) -> Dict[str, float]:
    """
    Torch wrapper for compute_checkerboard_metrics.
    
    Converts tensors to numpy and calls the numpy implementation.
    
    Args:
        real: (N, 2) real samples tensor
        gen: (M, 2) generated samples tensor
        domain: (xmin, xmax, ymin, ymax) bounding box
        cell_size: Size of each checkerboard cell
        parity: 0 or 1, determines which tiles are valid
        alpha: Dirichlet smoothing for histogram
        min_points_cell: Minimum real points in cell to compute ED
        max_points_cell: Optional cap on points per cell for speed
        lam: Weight for BV in CQS
        mu: Weight for WED_norm in CQS
        
    Returns:
        Dictionary of checkerboard metrics
    """
    X_real = real.detach().cpu().numpy()
    X_gen = gen.detach().cpu().numpy()
    
    return compute_checkerboard_metrics(
        X_real=X_real,
        X_gen=X_gen,
        domain=domain,
        cell_size=cell_size,
        parity=parity,
        alpha=alpha,
        min_points_cell=min_points_cell,
        max_points_cell=max_points_cell,
        lam=lam,
        mu=mu,
    )


# =============================================================================
# Image Metrics
# =============================================================================


def compute_nll(
    real_samples: np.ndarray,
    generated_samples: np.ndarray,
    n_pca_samples: int = 1000,
    n_components: int = 100,
) -> float:
    """
    Compute Negative Log-Likelihood using KDE with PCA preprocessing.
    
    This is a standard NLL metric for generative models that fits a KDE
    on the real data (in PCA space) and evaluates the likelihood of
    generated samples.
    
    Args:
        real_samples: (N, D) or (N, C, H, W) real samples
        generated_samples: (M, D) or (M, C, H, W) generated samples
        n_pca_samples: Number of real samples to use for PCA fitting
        n_components: Number of PCA components
        
    Returns:
        Negative log-likelihood (lower is better)
        
    Note:
        Returns infinity if computation fails.
    """
    if not SKLEARN_AVAILABLE or not SCIPY_AVAILABLE:
        print("Warning: sklearn or scipy not available for NLL computation")
        return float('inf')
    
    # Flatten to (N, D)
    real_samples = real_samples.reshape(real_samples.shape[0], -1)
    generated_samples = generated_samples.reshape(generated_samples.shape[0], -1)
    
    # Subsample real data for PCA fitting
    n_samples = min(n_pca_samples, real_samples.shape[0])
    rng = np.random.default_rng(42)
    idx = rng.choice(real_samples.shape[0], n_samples, replace=False)
    real_subset = real_samples[idx]
    
    # Determine number of PCA components
    n_components = min(n_components, real_subset.shape[1], n_samples - 1)
    
    try:
        # Fit PCA on real data
        pca = PCA(n_components=n_components, svd_solver='full')
        real_subset_pca = pca.fit_transform(real_subset)
        generated_samples_pca = pca.transform(generated_samples)
        
        # Check explained variance
        explained_variance_ratio = np.sum(pca.explained_variance_ratio_)
        if explained_variance_ratio < 0.8:
            print(f"Warning: PCA captured only {explained_variance_ratio:.4f} of variance")
        
        # Fit KDE on real data in PCA space
        kde = gaussian_kde(real_subset_pca.T)
        
        # Evaluate log-likelihood of generated samples
        log_likelihood = np.mean(kde.logpdf(generated_samples_pca.T))
        
        return float(-log_likelihood)
        
    except np.linalg.LinAlgError as e:
        print(f"KDE computation failed after PCA: {e}")
        return float('inf')
    except Exception as e:
        print(f"Error in NLL computation: {e}")
        return float('inf')


def compute_fid(
    real_images: Tensor,
    generated_images: Tensor,
    batch_size: int = 50,
    device: Optional[str] = None,
    dims: int = 2048,
) -> float:
    """
    Compute Fréchet Inception Distance (FID) for image data.
    
    FID measures the distance between feature distributions of real and
    generated images using InceptionV3. Lower is better.
    
    For grayscale images (e.g., MNIST), channels are repeated 3 times and
    images are resized to 299x299 for InceptionV3.
    
    Args:
        real_images: (N, C, H, W) or (N, H, W) or (N, D) real images in [0, 1]
        generated_images: (M, C, H, W) or (M, H, W) or (M, D) generated images in [0, 1]
        batch_size: Batch size for InceptionV3 forward pass
        device: Device to use (defaults to CUDA if available)
        dims: Feature dimensionality (2048 for pool3 layer)
        
    Returns:
        FID score (lower is better)
        
    Note:
        Returns -1 if torchvision is not available.
    """
    if not TORCHVISION_AVAILABLE:
        print("Warning: torchvision not available for FID computation")
        return -1.0
    
    if device is None:
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    
    # Convert numpy to tensor if needed
    if isinstance(real_images, np.ndarray):
        real_images = torch.from_numpy(real_images).float()
    if isinstance(generated_images, np.ndarray):
        generated_images = torch.from_numpy(generated_images).float()
    
    real_images = real_images.float()
    generated_images = generated_images.float()
    
    # Handle flattened images (e.g., MNIST as 784-dim vectors)
    # Detect MNIST: 784 = 28*28, Fashion-MNIST same
    if real_images.ndim == 2:
        d = real_images.shape[1]
        if d == 784:  # MNIST/Fashion-MNIST
            real_images = real_images.view(-1, 1, 28, 28)
            generated_images = generated_images.view(-1, 1, 28, 28)
        elif d == 3072:  # CIFAR (32*32*3)
            real_images = real_images.view(-1, 3, 32, 32)
            generated_images = generated_images.view(-1, 3, 32, 32)
        else:
            # Try to infer square image size
            h = int(np.sqrt(d))
            if h * h == d:
                real_images = real_images.view(-1, 1, h, h)
                generated_images = generated_images.view(-1, 1, h, h)
            else:
                print(f"Warning: Cannot infer image shape from {d}-dim vectors")
                return -1.0
    
    # Handle 3D tensors (N, H, W) -> (N, 1, H, W)
    if real_images.ndim == 3:
        real_images = real_images.unsqueeze(1)
    if generated_images.ndim == 3:
        generated_images = generated_images.unsqueeze(1)
    
    # Get image dimensions
    n_real, c_real, h_real, w_real = real_images.shape
    n_gen, c_gen, h_gen, w_gen = generated_images.shape
    
    # Load InceptionV3 model
    try:
        inception = tv_models.inception_v3(weights='IMAGENET1K_V1', transform_input=False)
        inception.fc = torch.nn.Identity()  # Remove classification layer
        inception = inception.to(device).eval()
    except Exception as e:
        print(f"Failed to load InceptionV3: {e}")
        return -1.0
    
    def preprocess_batch(images: Tensor) -> Tensor:
        """Preprocess images for InceptionV3."""
        # Ensure 4D: (N, C, H, W)
        if images.ndim == 3:
            images = images.unsqueeze(1)
        
        n, c, h, w = images.shape
        
        # Convert grayscale to RGB by repeating channels
        if c == 1:
            images = images.repeat(1, 3, 1, 1)
        
        # Resize to 299x299 (InceptionV3 input size)
        if h != 299 or w != 299:
            images = torch.nn.functional.interpolate(
                images, size=(299, 299), mode='bilinear', align_corners=False
            )
        
        # ImageNet normalization
        mean = torch.tensor([0.485, 0.456, 0.406], device=images.device).view(1, 3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225], device=images.device).view(1, 3, 1, 1)
        images = (images - mean) / std
        
        return images
    
    def get_activations(images: Tensor) -> np.ndarray:
        """Extract InceptionV3 features."""
        n_batches = (images.shape[0] + batch_size - 1) // batch_size
        activations = []
        
        for i in range(n_batches):
            start = i * batch_size
            end = min((i + 1) * batch_size, images.shape[0])
            batch = images[start:end].to(device)
            batch = preprocess_batch(batch)
            
            with torch.no_grad():
                # InceptionV3 returns (output, aux) in training mode
                # In eval mode, it returns just output
                act = inception(batch)
                if isinstance(act, tuple):
                    act = act[0]
            
            # Global average pooling if spatial dimensions remain
            if act.ndim == 4 and (act.shape[2] != 1 or act.shape[3] != 1):
                act = torch.nn.functional.adaptive_avg_pool2d(act, (1, 1))
            
            act = act.view(act.shape[0], -1)
            activations.append(act.cpu().numpy())
        
        return np.concatenate(activations, axis=0)
    
    try:
        # Get activations
        act_real = get_activations(real_images)
        act_gen = get_activations(generated_images)
        
        # Compute statistics
        mu_real = np.mean(act_real, axis=0)
        sigma_real = np.cov(act_real, rowvar=False)
        mu_gen = np.mean(act_gen, axis=0)
        sigma_gen = np.cov(act_gen, rowvar=False)
        
        # Handle single sample case
        if sigma_real.ndim == 0:
            sigma_real = np.array([[sigma_real]])
        if sigma_gen.ndim == 0:
            sigma_gen = np.array([[sigma_gen]])
        
        # Compute FID: ||mu_1 - mu_2||^2 + Tr(sigma_1 + sigma_2 - 2*sqrt(sigma_1 @ sigma_2))
        diff = mu_real - mu_gen
        mean_term = np.dot(diff, diff)
        
        # Matrix square root
        covmean, _ = linalg.sqrtm(sigma_real @ sigma_gen, disp=False)
        
        # Handle numerical issues
        if not np.isfinite(covmean).all():
            eps = 1e-6
            offset = np.eye(sigma_real.shape[0]) * eps
            covmean = linalg.sqrtm((sigma_real + offset) @ (sigma_gen + offset))
        
        # Take real part if complex
        if np.iscomplexobj(covmean):
            covmean = covmean.real
        
        cov_term = np.trace(sigma_real + sigma_gen - 2 * covmean)
        
        fid = float(mean_term + cov_term)
        
        return max(0.0, fid)  # FID should be non-negative
        
    except Exception as e:
        print(f"Error in FID computation: {e}")
        return -1.0


def sliced_wasserstein_distance(
    real: Tensor,
    gen: Tensor,
    n_projections: int = 1000,
) -> float:
    """
    Sliced Wasserstein Distance for images.

    Projects high-dimensional data onto random 1D directions and
    computes average 1D Wasserstein distance. This is a fast
    approximation to the true Wasserstein distance.

    Args:
        real: (N, C, H, W) or (N, D) real samples
        gen: (M, C, H, W) or (M, D) generated samples
        n_projections: Number of random projections

    Returns:
        SWD estimate

    Example
    -------
    >>> swd = sliced_wasserstein_distance(real_images, gen_images)
    """
    # Flatten if needed
    if real.ndim > 2:
        real = real.view(real.shape[0], -1)
    if gen.ndim > 2:
        gen = gen.view(gen.shape[0], -1)

    real = real.float().cpu()
    gen = gen.float().cpu()

    d = real.shape[1]

    # Random projection directions (unit vectors)
    directions = torch.randn(n_projections, d)
    directions = directions / directions.norm(dim=1, keepdim=True)

    # Project data
    real_proj = real @ directions.T  # (N, n_proj)
    gen_proj = gen @ directions.T  # (M, n_proj)

    # Sort projections
    real_sorted = torch.sort(real_proj, dim=0)[0]
    gen_sorted = torch.sort(gen_proj, dim=0)[0]

    # Handle different sample sizes by interpolation
    n, m = real_sorted.shape[0], gen_sorted.shape[0]
    if n != m:
        # Interpolate to same size
        size = min(n, m)
        real_idx = torch.linspace(0, n - 1, size).long()
        gen_idx = torch.linspace(0, m - 1, size).long()
        real_sorted = real_sorted[real_idx]
        gen_sorted = gen_sorted[gen_idx]

    # Compute 1D Wasserstein (L2 distance between sorted samples)
    swd = (real_sorted - gen_sorted).pow(2).mean(dim=0).sqrt().mean()

    return float(swd)


def compute_image_statistics(images: Tensor) -> Dict[str, float]:
    """
    Compute basic image statistics.

    Args:
        images: (N, C, H, W) images

    Returns:
        Dictionary with mean, std, min, max
    """
    images = images.float()

    return {
        "mean": float(images.mean()),
        "std": float(images.std()),
        "min": float(images.min()),
        "max": float(images.max()),
    }


def compute_image_metrics(
    real: Tensor,
    gen: Tensor,
    n_projections: int = 1000,
    compute_expensive: bool = True,
    fid_batch_size: int = 50,
) -> Dict[str, float]:
    """
    Compute image generation metrics including SWD, NLL, and FID.

    Args:
        real: (N, C, H, W) or (N, D) real images
        gen: (M, C, H, W) or (M, D) generated images
        n_projections: Number of projections for SWD
        compute_expensive: If True, compute FID (requires InceptionV3)
        fid_batch_size: Batch size for FID computation

    Returns:
        Dictionary of metrics including:
        - real_mean, real_std: Statistics of real images
        - gen_mean, gen_std: Statistics of generated images
        - swd: Sliced Wasserstein Distance
        - swd_r, swd_g, swd_b: Per-channel SWD (for RGB)
        - nll: Negative Log-Likelihood (KDE-based)
        - fid: Fréchet Inception Distance

    Example
    -------
    >>> metrics = compute_image_metrics(real_images, gen_images)
    >>> print(f"SWD: {metrics['swd']:.4f}")
    >>> print(f"FID: {metrics['fid']:.4f}")
    >>> print(f"NLL: {metrics['nll']:.4f}")
    """
    metrics: Dict[str, float] = {}

    # Basic statistics
    real_stats = compute_image_statistics(real)
    gen_stats = compute_image_statistics(gen)

    metrics["real_mean"] = real_stats["mean"]
    metrics["real_std"] = real_stats["std"]
    metrics["gen_mean"] = gen_stats["mean"]
    metrics["gen_std"] = gen_stats["std"]

    # Sliced Wasserstein Distance
    metrics["swd"] = sliced_wasserstein_distance(real, gen, n_projections)

    # Per-channel SWD for RGB
    if real.ndim == 4 and real.shape[1] == 3:
        for c, name in enumerate(["r", "g", "b"]):
            metrics[f"swd_{name}"] = sliced_wasserstein_distance(
                real[:, c : c + 1], gen[:, c : c + 1], n_projections // 3
            )

    # =========================================================================
    # NLL (Negative Log-Likelihood) using KDE with PCA
    # =========================================================================
    try:
        real_np = real.detach().cpu().numpy()
        gen_np = gen.detach().cpu().numpy()
        nll = compute_nll(real_np, gen_np)
        metrics["nll"] = nll
    except Exception as e:
        print(f"Warning: NLL computation failed: {e}")
        metrics["nll"] = float('inf')

    # =========================================================================
    # FID (Fréchet Inception Distance)
    # =========================================================================
    if compute_expensive and TORCHVISION_AVAILABLE:
        try:
            fid = compute_fid(real, gen, batch_size=fid_batch_size)
            metrics["fid"] = fid
        except Exception as e:
            print(f"Warning: FID computation failed: {e}")
            metrics["fid"] = -1.0
    elif not TORCHVISION_AVAILABLE:
        print("Warning: torchvision not available, skipping FID")
        metrics["fid"] = -1.0

    return metrics


# =============================================================================
# Unified Interface
# =============================================================================


def compute_metrics(
    real: Tensor,
    gen: Tensor,
    is_image: bool = False,
    n_projections: int = 1000,
    checkerboard_config: Optional[Dict] = None,
) -> Dict[str, float]:
    """
    Compute appropriate metrics based on data type.

    This is the main entry point for metric computation. It automatically
    selects the appropriate metrics based on whether the data is images
    or point clouds.

    Args:
        real: Real samples
        gen: Generated samples
        is_image: If True, use image metrics (SWD)
        n_projections: Number of projections for SWD
        checkerboard_config: If provided, compute checkerboard metrics for point data.
            Should contain: domain, cell_size, parity, lam, mu

    Returns:
        Dictionary of metrics

    Example
    -------
    >>> # For point cloud data
    >>> metrics = compute_metrics(real_points, gen_points, is_image=False)
    >>> print(f"W2: {metrics['wasserstein_2d']:.4f}")

    >>> # For image data
    >>> metrics = compute_metrics(real_images, gen_images, is_image=True)
    >>> print(f"SWD: {metrics['swd']:.4f}")
    
    >>> # For checkerboard data
    >>> cb_config = {"domain": (-4, 4, -4, 4), "cell_size": 1.0, "parity": 0}
    >>> metrics = compute_metrics(real, gen, checkerboard_config=cb_config)
    >>> print(f"CQS: {metrics['CQS']:.4f}")
    """
    if is_image or real.ndim >= 3:
        return compute_image_metrics(real, gen, n_projections)
    else:
        return compute_point_metrics(real, gen, checkerboard_config=checkerboard_config)


# =============================================================================
# Additional Metrics for Research
# =============================================================================


def compute_energy_distance(x: Tensor, y: Tensor) -> float:
    """
    Compute energy distance between two distributions.

    Energy distance is an alternative to MMD that is based on
    Euclidean distances rather than kernel evaluations.

    Args:
        x: (N, D) samples from P
        y: (M, D) samples from Q

    Returns:
        Energy distance

    Example
    -------
    >>> ed = compute_energy_distance(real, gen)
    """
    x = x.float()
    y = y.float()

    # Pairwise distances
    xx = torch.cdist(x, x, p=2).mean()
    yy = torch.cdist(y, y, p=2).mean()
    xy = torch.cdist(x, y, p=2).mean()

    # Energy distance formula
    ed = 2 * xy - xx - yy

    return float(max(0.0, ed))


def compute_frechet_distance(
    mu1: Tensor,
    sigma1: Tensor,
    mu2: Tensor,
    sigma2: Tensor,
    eps: float = 1e-6,
) -> float:
    """
    Compute Fréchet distance between two Gaussian distributions.

    This is the building block for FID (Fréchet Inception Distance).

    FD(μ₁, Σ₁, μ₂, Σ₂) = ||μ₁ - μ₂||² + Tr(Σ₁ + Σ₂ - 2(Σ₁Σ₂)^{1/2})

    Args:
        mu1: Mean of first distribution
        sigma1: Covariance of first distribution
        mu2: Mean of second distribution
        sigma2: Covariance of second distribution
        eps: Small constant for numerical stability

    Returns:
        Fréchet distance
    """
    if not SCIPY_AVAILABLE:
        return -1.0

    mu1 = mu1.cpu().numpy()
    sigma1 = sigma1.cpu().numpy()
    mu2 = mu2.cpu().numpy()
    sigma2 = sigma2.cpu().numpy()

    # Mean difference
    diff = mu1 - mu2
    mean_term = diff @ diff

    # Covariance term
    covmean, _ = linalg.sqrtm(sigma1 @ sigma2, disp=False)

    # Handle numerical issues
    if not np.isfinite(covmean).all():
        offset = np.eye(sigma1.shape[0]) * eps
        covmean = linalg.sqrtm((sigma1 + offset) @ (sigma2 + offset))

    if np.iscomplexobj(covmean):
        covmean = covmean.real

    cov_term = np.trace(sigma1 + sigma2 - 2 * covmean)

    return float(mean_term + cov_term)


def compute_log_likelihood_estimate(
    samples: Tensor,
    reference_samples: Tensor,
    bandwidth: Optional[float] = None,
) -> float:
    """
    Estimate log-likelihood using kernel density estimation.

    This provides a rough estimate of how well the generated samples
    fit the reference distribution.

    Args:
        samples: Samples to evaluate
        reference_samples: Reference samples defining the distribution
        bandwidth: KDE bandwidth (if None, uses Scott's rule)

    Returns:
        Average log-likelihood estimate
    """
    samples = samples.float()
    reference_samples = reference_samples.float()

    n_ref = reference_samples.shape[0]
    d = samples.shape[1]

    # Scott's rule for bandwidth
    if bandwidth is None:
        bandwidth = n_ref ** (-1 / (d + 4)) * reference_samples.std()
        bandwidth = max(bandwidth, 1e-3)

    # Compute pairwise distances
    dists = torch.cdist(samples, reference_samples, p=2)

    # Gaussian kernel density estimate
    log_kernels = -0.5 * (dists / bandwidth) ** 2
    log_density = torch.logsumexp(log_kernels, dim=1) - np.log(n_ref)
    log_density -= d / 2 * np.log(2 * np.pi) + d * np.log(bandwidth)

    return float(log_density.mean())


# =============================================================================
# Bits Per Dimension (BPD) - Exact Likelihood Evaluation
# =============================================================================


def compute_bpd_from_model(
    model: "UVStabilizedFlowMatchingModel",
    data_loader: torch.utils.data.DataLoader,
    n_hutchinson_samples: int = 1,
    max_batches: Optional[int] = None,
    device: Optional[torch.device] = None,
) -> Dict[str, float]:
    """
    Compute bits per dimension (BPD) using exact log-likelihood.

    BPD measures how many bits are needed on average to encode each dimension
    of the data under the model. Lower is better.

    BPD = -log₂ p(x) / D = -log p(x) / (D × log(2))

    This uses the change of variables formula for continuous normalizing flows:
        log p(x) = log p(z) - ∫ div(v(z, r)) dr

    where z is the latent (at IR) and x is the data (at UV).

    Args:
        model: Trained flow matching model
        data_loader: DataLoader providing data samples
        n_hutchinson_samples: Number of random vectors for Hutchinson trace estimator
        max_batches: Maximum number of batches to evaluate (None = all)
        device: Device to use for computation

    Returns:
        Dict containing:
            - 'bpd': Mean bits per dimension
            - 'bpd_std': Standard deviation of BPD
            - 'log_likelihood': Mean log likelihood
            - 'log_prior': Mean log prior
            - 'log_det_jacobian': Mean log det Jacobian
            - 'n_samples': Number of samples evaluated
    """
    model.eval()
    
    if device is None:
        device = next(model.parameters()).device

    all_bpd = []
    all_log_likelihood = []
    all_log_prior = []
    all_log_det_jacobian = []

    # NOTE: Do NOT use torch.no_grad() here because compute_log_likelihood
    # uses torch.autograd.grad() for the Hutchinson trace estimator
    for batch_idx, batch in enumerate(data_loader):
        if max_batches is not None and batch_idx >= max_batches:
            break

        # Handle both (data,) and (data, label) formats
        if isinstance(batch, (tuple, list)):
            data = batch[0]
        else:
            data = batch

        data = data.to(device)

        # Compute BPD for this batch
        bpd, info = model.compute_bpd(
            data, n_hutchinson_samples=n_hutchinson_samples
        )

        all_bpd.append(bpd.cpu())
        all_log_likelihood.append(info["log_likelihood"].cpu())
        all_log_prior.append(info["log_prior"].cpu())
        all_log_det_jacobian.append(info["log_det_jacobian"].cpu())

    # Concatenate all results
    all_bpd = torch.cat(all_bpd)
    all_log_likelihood = torch.cat(all_log_likelihood)
    all_log_prior = torch.cat(all_log_prior)
    all_log_det_jacobian = torch.cat(all_log_det_jacobian)

    # Filter out invalid values (inf, nan)
    valid_mask = torch.isfinite(all_bpd)
    if valid_mask.sum() < len(all_bpd):
        print(f"Warning: {(~valid_mask).sum()} samples had invalid BPD values")
    
    valid_bpd = all_bpd[valid_mask]
    valid_ll = all_log_likelihood[valid_mask]
    valid_prior = all_log_prior[valid_mask]
    valid_det = all_log_det_jacobian[valid_mask]

    return {
        "bpd": float(valid_bpd.mean()) if len(valid_bpd) > 0 else float("inf"),
        "bpd_std": float(valid_bpd.std()) if len(valid_bpd) > 0 else float("inf"),
        "log_likelihood": float(valid_ll.mean()) if len(valid_ll) > 0 else float("-inf"),
        "log_prior": float(valid_prior.mean()) if len(valid_prior) > 0 else float("-inf"),
        "log_det_jacobian": float(valid_det.mean()) if len(valid_det) > 0 else 0.0,
        "n_samples": int(valid_mask.sum()),
        "n_invalid": int((~valid_mask).sum()),
    }


def compute_bpd_direct(
    log_likelihood: Tensor,
    data_dim: int,
) -> Tensor:
    """
    Convert log-likelihood to bits per dimension.

    Args:
        log_likelihood: (B,) log p(x) values
        data_dim: Dimensionality of data

    Returns:
        bpd: (B,) bits per dimension
    """
    return -log_likelihood / (data_dim * np.log(2))
